// flow-typed signature: f12fc066a61f1fb2d6166e621eff3cee
// flow-typed version: <<STUB>>/@octokit/graphql_v4.5.7/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@octokit/graphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@octokit/graphql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@octokit/graphql/dist-node' {
  declare module.exports: any;
}

declare module '@octokit/graphql/dist-src/error' {
  declare module.exports: any;
}

declare module '@octokit/graphql/dist-src/graphql' {
  declare module.exports: any;
}

declare module '@octokit/graphql/dist-src' {
  declare module.exports: any;
}

declare module '@octokit/graphql/dist-src/types' {
  declare module.exports: any;
}

declare module '@octokit/graphql/dist-src/version' {
  declare module.exports: any;
}

declare module '@octokit/graphql/dist-src/with-defaults' {
  declare module.exports: any;
}

declare module '@octokit/graphql/dist-web' {
  declare module.exports: any;
}

// Filename aliases
declare module '@octokit/graphql/dist-node/index' {
  declare module.exports: $Exports<'@octokit/graphql/dist-node'>;
}
declare module '@octokit/graphql/dist-node/index.js' {
  declare module.exports: $Exports<'@octokit/graphql/dist-node'>;
}
declare module '@octokit/graphql/dist-src/error.js' {
  declare module.exports: $Exports<'@octokit/graphql/dist-src/error'>;
}
declare module '@octokit/graphql/dist-src/graphql.js' {
  declare module.exports: $Exports<'@octokit/graphql/dist-src/graphql'>;
}
declare module '@octokit/graphql/dist-src/index' {
  declare module.exports: $Exports<'@octokit/graphql/dist-src'>;
}
declare module '@octokit/graphql/dist-src/index.js' {
  declare module.exports: $Exports<'@octokit/graphql/dist-src'>;
}
declare module '@octokit/graphql/dist-src/types.js' {
  declare module.exports: $Exports<'@octokit/graphql/dist-src/types'>;
}
declare module '@octokit/graphql/dist-src/version.js' {
  declare module.exports: $Exports<'@octokit/graphql/dist-src/version'>;
}
declare module '@octokit/graphql/dist-src/with-defaults.js' {
  declare module.exports: $Exports<'@octokit/graphql/dist-src/with-defaults'>;
}
declare module '@octokit/graphql/dist-web/index' {
  declare module.exports: $Exports<'@octokit/graphql/dist-web'>;
}
declare module '@octokit/graphql/dist-web/index.js' {
  declare module.exports: $Exports<'@octokit/graphql/dist-web'>;
}
