// flow-typed signature: 35bf474d1f87c662dec8840f4d42d65b
// flow-typed version: <<STUB>>/@octokit/rest_v18.0.9/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@octokit/rest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@octokit/rest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@octokit/rest/dist-node' {
  declare module.exports: any;
}

declare module '@octokit/rest/dist-src' {
  declare module.exports: any;
}

declare module '@octokit/rest/dist-src/version' {
  declare module.exports: any;
}

declare module '@octokit/rest/dist-web' {
  declare module.exports: any;
}

// Filename aliases
declare module '@octokit/rest/dist-node/index' {
  declare module.exports: $Exports<'@octokit/rest/dist-node'>;
}
declare module '@octokit/rest/dist-node/index.js' {
  declare module.exports: $Exports<'@octokit/rest/dist-node'>;
}
declare module '@octokit/rest/dist-src/index' {
  declare module.exports: $Exports<'@octokit/rest/dist-src'>;
}
declare module '@octokit/rest/dist-src/index.js' {
  declare module.exports: $Exports<'@octokit/rest/dist-src'>;
}
declare module '@octokit/rest/dist-src/version.js' {
  declare module.exports: $Exports<'@octokit/rest/dist-src/version'>;
}
declare module '@octokit/rest/dist-web/index' {
  declare module.exports: $Exports<'@octokit/rest/dist-web'>;
}
declare module '@octokit/rest/dist-web/index.js' {
  declare module.exports: $Exports<'@octokit/rest/dist-web'>;
}
