// flow-typed signature: 50835ddadfea0f8fd3f47a8cd808eefb
// flow-typed version: <<STUB>>/@adobe/aio-lib-core-config_v^2.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@adobe/aio-lib-core-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@adobe/aio-lib-core-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@adobe/aio-lib-core-config/src/Config' {
  declare module.exports: any;
}

declare module '@adobe/aio-lib-core-config/src/dotenv' {
  declare module.exports: any;
}

declare module '@adobe/aio-lib-core-config/src' {
  declare module.exports: any;
}

declare module '@adobe/aio-lib-core-config/src/pipe' {
  declare module.exports: any;
}

declare module '@adobe/aio-lib-core-config/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@adobe/aio-lib-core-config/src/Config.js' {
  declare module.exports: $Exports<'@adobe/aio-lib-core-config/src/Config'>;
}
declare module '@adobe/aio-lib-core-config/src/dotenv.js' {
  declare module.exports: $Exports<'@adobe/aio-lib-core-config/src/dotenv'>;
}
declare module '@adobe/aio-lib-core-config/src/index' {
  declare module.exports: $Exports<'@adobe/aio-lib-core-config/src'>;
}
declare module '@adobe/aio-lib-core-config/src/index.js' {
  declare module.exports: $Exports<'@adobe/aio-lib-core-config/src'>;
}
declare module '@adobe/aio-lib-core-config/src/pipe.js' {
  declare module.exports: $Exports<'@adobe/aio-lib-core-config/src/pipe'>;
}
declare module '@adobe/aio-lib-core-config/src/util.js' {
  declare module.exports: $Exports<'@adobe/aio-lib-core-config/src/util'>;
}
