// flow-typed signature: 466cbb89c0f960b8f1116dbc64821b8c
// flow-typed version: <<STUB>>/@adobe/aio-lib-core-logging_v1.1.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@adobe/aio-lib-core-logging'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@adobe/aio-lib-core-logging' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@adobe/aio-lib-core-logging/src/AioLogger' {
  declare module.exports: any;
}

declare module '@adobe/aio-lib-core-logging/src/DebugLogger' {
  declare module.exports: any;
}

declare module '@adobe/aio-lib-core-logging/src/WinstonLogger' {
  declare module.exports: any;
}

declare module '@adobe/aio-lib-core-logging/test/AioLogger.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@adobe/aio-lib-core-logging/src/AioLogger.js' {
  declare module.exports: $Exports<'@adobe/aio-lib-core-logging/src/AioLogger'>;
}
declare module '@adobe/aio-lib-core-logging/src/DebugLogger.js' {
  declare module.exports: $Exports<'@adobe/aio-lib-core-logging/src/DebugLogger'>;
}
declare module '@adobe/aio-lib-core-logging/src/WinstonLogger.js' {
  declare module.exports: $Exports<'@adobe/aio-lib-core-logging/src/WinstonLogger'>;
}
declare module '@adobe/aio-lib-core-logging/test/AioLogger.test.js' {
  declare module.exports: $Exports<'@adobe/aio-lib-core-logging/test/AioLogger.test'>;
}
