name: flow-check

on:
    pull_request:
    push:
        branches:
            - master
            - develop

jobs:
    test:
        name: Run Flow type checking
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm install
            - name: Run flow check
              run: npm run flow:check
